linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - shadow

linters-settings:
  govet:
    enable-all: true
    fieldalignment: true

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor/
    - third_party/
  exclude-files:
    - ".*_test\\.go$"

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true
