name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      - name: Run tests
        run: make test

  build:
    name: Build and Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build all platforms
        run: |
          mkdir -p bin
          echo "Running cross-build..."
          make cross-build
          echo "Cross-build complete. Listing bin directory:"
          ls -la bin/
          if [ -z "$(ls -A bin/)" ]; then
            echo "Error: No files were created in bin directory"
            exit 1
          fi

      - name: Generate checksums
        run: |
          cd bin
          echo "Generating checksums for files:"
          ls -la
          sha256sum * > ../sha256sums.txt || {
            echo "Error generating checksums. Contents of bin directory:"
            ls -la
            exit 1
          }
          cd ..
          echo "Generated checksums:"
          cat sha256sums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*
            sha256sums.txt
          draft: false
          prerelease: false
          generate_release_notes: true

  docker:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ncecere/bullnose
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
